export default {
    // journal actions
    ADD_JOURNAL_POST: 'ADD_JOURNAL_POST',
    UPDATE_JOURNAL: 'UPDATE_JOURNAL',
    REMOVE_JOURNAL_POST: 'REMOVE_JOURNAL_POST',
    SET_CURRENT_POST: 'SET_CURRENT_POST',
    // user actions
    ADD_ARTWORK: 'ADD_ARTWORK',
    UPDATE_ARTWORK: 'UPDATE_ARTWORK',
    REMOVE_ARTWORK: 'REMOVE_ARTWORK',
    SET_CURRENT_ARTWORK: 'SET_CURRENT_ARTWORK',
    // artwork actions
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    REMOVE_USER: 'REMOVE_USER',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
}